version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: db # Replace with your desired database name
      MYSQL_USER: user # Replace with your desired MySQL username
      MYSQL_PASSWORD: password # Replace with your desired MySQL password
      MYSQL_ROOT_PASSWORD: password # Replace with your desired root password
    ports:
      - '3306:3306' # <Port exposed> : <MySQL Port running inside container>
    expose:
      - '3306' # Opens port 3306 on the container
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
